<?php
/**
 * Copyright © Pixl Mods. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \PixlMods\Popup\Block\Frontend\Popup $block */
$popupsJson = $block->getPopupsDataJson();
?>

<?php if ($popupsJson !== '[]'): ?>
    <div id="pixlmods-popup-container"></div>

    <script type="text/x-magento-init">
        {
            "#pixlmods-popup-container": {
                "PixlMods_Popup/js/view/popup": {
                    "popups": <?= /* @noEscape */ $popupsJson ?>,
                    "eventUrl": "<?= $block->escapeUrl($block->getUrl('pixlmodspopup/report/event')) ?>",
                    "dayCookieLifetime": <?= (int) $block->getDayFrequencyLifetime() ?>
                }
            }
        }
    </script>
<?php endif; ?>
